FROM openjdk:8

COPY springboot-helloworld-master/target/helloworld-0.0.1-SNAPSHOT.jar /data/springboot-helloworld
WORKDIR /data/springboot-helloworld

RUN ls -ltR /data/springboot-helloworld

EXPOSE 8080

CMD ["java", "-jar", "helloworld-0.0.1-SNAPSHOT.jar"]
