FROM openjdk:8

COPY . /data/springboot-helloworld
WORKDIR /data/springboot-helloworld

RUN ls -ltR /data/springboot-helloworld

EXPOSE 8080

CMD ["java", "-jar", "target/helloworld-0.0.1-SNAPSHOT.jar"]
